import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'es' | 'en';

export interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string, fallbackOrVars?: string | Record<string, any>, vars?: Record<string, any>) => string;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    // Top Navbar
    'nav.title': 'Moodle Agenda',
    'nav.subtitle': 'Gestor de Aula Virtual Moodle',
    'nav.disconnected': 'Moodle Desconectado',
    'nav.setActive': 'Hacer activo: {username}',
    'nav.notifications': 'Notificaciones de cambios',
    'nav.activityAlerts': 'Alertas de Actividades',
    'nav.markRead': 'Marcar leídas',
    'nav.clear': 'Limpiar',
    'nav.integratedNotifications': '🔔 Notificaciones integradas',
    'nav.notificationsEnabled': 'Activadas',
    'nav.notificationsEnableBtn': 'Habilitar',
    'nav.noNotifications': '¡Sin notificaciones!',
    'nav.noNotificationsDesc': 'Aquí se anunciarán los cambios en tus materias cada vez que sincronices.',
    'nav.smartAlerts': 'Alertas Inteligentes Moodle',
    'nav.notifBrowserGranted': '¡Notificaciones del navegador activadas!',
    'nav.notifBrowserPrompt': 'Por favor, habilita las notificaciones en el candado de la URL de tu navegador.',
    'nav.switchLanguage': 'Cambiar idioma',

    // Main Navigation Tabs
    'tab.agenda': 'Mi Agenda',
    'tab.connections': 'Conexiones',
    'tab.stats': 'Estadísticas',
    'tab.sandbox': 'Sandbox',
    'tab.newTask': '+ Nueva Tarea',
    'tab.newTaskTitle': 'Crear nueva actividad manual',

    // SyncStatusBar
    'sync.syncBtn': 'Sincronizar',
    'sync.syncingBtn': 'Sincronizando...',
    'sync.connectFirst': 'Conecta una cuenta primero',
    'sync.syncAllActive': 'Sincronizar materias de todas las cuentas activas',
    'sync.account': 'cuenta',
    'sync.accounts': 'cuentas',
    'sync.viewAccountDetails': 'Ver detalles por cuenta',
    'sync.lastSynced': 'Última vez: {time}',
    'sync.notSyncedRecently': 'Sin sincronizar recientemente',
    'sync.tasksCompleted': '({completed}/{total} completadas)',
    'sync.legendTitle': 'Guía de iconos y estados',
    'sync.icons': 'Iconos',
    'sync.legendHeading': 'Guía de Indicadores',
    'sync.legend.imminent': 'Inminente (<30h)',
    'sync.legend.excellent': 'Excelente (≥90%)',
    'sync.legend.pending': 'Pendiente (<10d)',
    'sync.legend.acceptable': 'Aceptable (80-89%)',
    'sync.legend.ungraded': 'Sin calificar',
    'sync.legend.regular': 'Regular (60-79%)',
    'sync.legend.overdue': 'Vencido',
    'sync.legend.failed': 'Reprobado (<60%)',
    'sync.progressOf': '{current} de {total} materias',
    'sync.cancel': 'Cancelar',
    'sync.connecting': 'Conectando con Moodle...',
    'sync.analyzing': 'Analizando actividades...',
    'sync.upToDate': 'Al día',
    'sync.error': 'Error',
    'sync.ready': 'Listo',
    'sync.viewLog': 'Ver registro',
    'sync.emptyBanner': 'Conecta tu cuenta de Moodle para sincronizar automáticamente tus materias y tareas.',
    'sync.connect': 'Conectar',

    // Relative times
    'time.justNow': 'hace un momento',
    'time.minutesAgo': 'hace {min}m',
    'time.hoursAgo': 'hace {hrs} hrs',
    'time.daysAgo': 'hace {days} d',
    'time.completed': 'Completado',
    'time.noDeadline': 'Sin fecha de cierre',
    'time.closedOverdue': 'Cerrado/Vencido',
    'time.oneDayHrsLeft': 'Falta 1 día y {hrs} hrs',
    'time.daysLeft': 'Faltan {days} días',
    'time.minutesLeft': '¡Faltan {mins} minutos!',
    'time.hoursLeft': '¡Faltan {hrs} horas!',

    // Connections List in App.tsx
    'conn.connectedAccounts': 'Cuentas Conectadas ({count})',
    'conn.verifyingSession': 'Verificando sesión...',
    'conn.sessionExpired': '(Sesión Expirada)',
    'conn.currentBrowser': '(Navegador Actual)',
    'conn.reconnect': 'Reconectar',
    'conn.viewActivities': 'Ver actividades',
    'conn.viewBrowser': 'Ver navegador',
    'conn.removeAccount': 'Quitar Cuenta',
    'conn.logOut': 'Cerrar Sesión',

    // Developer Sandbox in App.tsx
    'dev.title': 'Developer Sandbox & Registro de Eventos',
    'dev.desc': 'Explora Moodle interactivamente a través de nuestro proxy de seguridad. Todas tus interacciones (clicks en botones, enlaces, y metadatos de archivos que cargues) se registrarán en tiempo real en la consola de eventos para su análisis técnico.',
    'dev.clearConfirm': '¿Estás seguro de que deseas limpiar el historial de logs de eventos?',
    'dev.clearBtn': 'Limpiar Logs',
    'dev.clearTooltip': 'Borrar todos los eventos registrados',
    'dev.noConnectionsTitle': 'Sin Conexiones Activas de Moodle',
    'dev.noConnectionsDesc': 'Esta sección requiere un navegador de Moodle conectado. Ve a la sección de Conexión de Moodle para iniciar sesión con tus credenciales.',
    'dev.connectNowBtn': 'Conectar Moodle Ahora',
    'dev.activeSessionLabel': 'Sesión Activa:',
    'dev.homeDashboardTooltip': 'Ir al home dashboard (/my/)',
    'dev.reloadTooltip': 'Recargar página',
    'dev.proxyLabel': 'PROXY HTTP',
    'dev.goBtn': 'Ir',
    'dev.loadingProxy': 'Cargando navegador proxy de Moodle...',
    'dev.eventLogsTitle': 'Log de Eventos Detectados',
    'dev.eventsCount': '{count} eventos',
    'dev.userInteractionsDesc': 'Interacciones del usuario registradas:',
    'dev.copyJson': 'Copiar JSON',
    'dev.copiedSuccess': 'Logs copiados al portapapeles con éxito.',
    'dev.waitingInteractions': 'Esperando interacciones en el navegador...',
    'dev.waitingInteractionsDesc': 'Haz click en materias, botones u opte por subir archivos para ver el log en vivo.',
    'dev.element': 'Elemento:',
    'dev.id': 'ID:',
    'dev.class': 'Clase:',
    'dev.href': 'Href:',
    'dev.field': 'Campo:',
    'dev.size': 'Tamaño:',
    'dev.type': 'Tipo:',
    'dev.untitled': '(Sin título)',

    // ActivityTimeline
    'timeline.localTime': 'Hora local (Ecuador):',
    'timeline.searchPlaceholder': 'Buscar actividad...',
    'timeline.accountsFilter': 'Cuentas',
    'timeline.allCourses': 'Todas las Materias',
    'timeline.allTypes': 'Todos los Tipos',
    'timeline.typeTask': 'Tareas',
    'timeline.typeQuiz': 'Cuestionarios',
    'timeline.typeActivity': 'Actividades',
    'timeline.typeManual': 'Manuales',
    'timeline.done': 'Hechas',
    'timeline.hideCompleted': 'Ocultar completadas',
    'timeline.showCompleted': 'Mostrar completadas',
    'timeline.downloadCsv': 'Descargar CSV',
    'timeline.clearAgenda': 'Limpiar Agenda',
    'timeline.confirmClear': '¿CONFIRMAR BORRAR AGENDA?',
    'timeline.filterByAccount': 'Filtrar por cuenta:',
    'timeline.allAccounts': 'Todas las Cuentas ({count})',
    'timeline.activeFilters': '{count} filtro{plural} activo{plural}',
    'timeline.filterAccountsTitle': 'Filtrar Cuentas / Carreras',
    'timeline.noOptions': 'No hay opciones disponibles',
    'timeline.manualTasks': 'Tareas Manuales / Locales',
    'timeline.manualTasksCareer': 'Tareas Manuales ({carrera})',
    'timeline.other': 'Otros',
    'timeline.statsPending': '{count} pendientes',
    'timeline.statsCompleted': '{count} completadas',
    'timeline.statsProgress': '{percent}% progreso',
    'timeline.weekTitle': 'Semana {number}',
    'timeline.weekSpecial': 'Semana Especial / Extra',
    'timeline.weekNoDeadline': 'Actividades sin fecha de cierre específica',
    'timeline.currentWeekBadge': 'Semana actual',
    'timeline.groupBadge': 'Grupal',
    'timeline.opening': 'Abriendo...',
    'timeline.updating': 'Actualizando...',
    'timeline.downloading': 'Descargando...',
    'timeline.viewDocument': 'Ver documento',
    'timeline.downloadHtml': 'Descargar HTML',
    'timeline.rescan': 'Re-escanear',
    'timeline.viewInMoodle': 'Ver en Moodle',
    'timeline.grade': 'Nota:',
    'timeline.feedback': 'Retroalimentación:',
    'timeline.attachedFeedbackImages': 'Imágenes de retroalimentación:',
    'timeline.aperture': 'Apertura:',
    'timeline.closure': 'Cierre:',
    'timeline.importantNotice': 'Aviso importante:',
    'timeline.noFilteredActivities': 'Sin actividades que coincidan con los filtros',
    'timeline.emptyAgendaTitle': '¡Tu agenda está vacía!',
    'timeline.emptyAgendaDesc': 'Ve a "Explorar Moodle" y presiona "Sincronizar Todas las Materias" o agrega una tarea manual.',
    'timeline.clearAgendaConfirm': '¿Estás seguro de que deseas limpiar toda la agenda local?',
    'timeline.reopenedWarning': '⚠️ Esta tarea venció, pero está abierta para entrega extemporánea o segundo intento.',
    'timeline.overdueWarning': '⚠️ Esta tarea ya cerró su plazo oficial de entrega.',
    'timeline.viewRawHtml': 'Ver HTML',

    // StatsPanel
    'stats.title': 'Rendimiento Académico por Materia',
    'stats.subtitle': 'Tus materias ordenadas de menor a mayor promedio. Los trabajos no entregados vencidos penalizan con',
    'stats.filterLabel': 'Filtrar rendimiento por cuenta:',
    'stats.allAccounts': 'Todas las Cuentas ({count})',
    'stats.activeFilters': '{count} filtro{plural} activo{plural}',
    'stats.filterModalTitle': 'Filtrar Cuentas / Carreras',
    'stats.clear': 'Limpiar',
    'stats.noOptions': 'No hay opciones disponibles',
    'stats.manualTasksLocal': 'Tareas Manuales / Locales',
    'stats.manualTasksCareer': 'Tareas Manuales ({carrera})',
    'stats.emptyAlert': 'Aún no se registran actividades calificadas o vencidas en tu agenda.',
    'stats.emptyAlertSub': 'Sincroniza tus materias en "Explorar Moodle" para descargar tus notas reales.',
    'stats.highestAlert': 'Mayor Alerta ⭐',
    'stats.generalAvg': 'Promedio General 📈',
    'stats.totalAccumulated': 'Acumulado Total',
    'stats.bestPerformance': 'Mejor Rendimiento ✨',
    'stats.courseLabel': 'Materia {number}',
    'stats.unsubmitted': '{count} sin entregar',
    'stats.graded': '{count} calificado{plural}',
    'stats.noGrades': 'Sin calificaciones',
    'stats.breakdown': 'Desglose de Calificaciones ({count} ítems analizados)',
    'stats.viewUpcoming': 'Ver próximas actividades',
    'stats.noCourseGrades': 'No hay notas registradas para esta materia.',
    'stats.overdueUnsubmitted': 'No entregado (Vencido)',
    'stats.moodleGrade': 'Nota de Moodle',
    'stats.closedDate': 'Cerró: {date}',

    // LoginPanel
    'login.connected': 'Moodle Conectado',
    'login.user': 'Usuario:',
    'login.disconnect': 'Desconectar',
    'login.connectTitle': 'Conectar Aula Virtual',
    'login.connectSubtitle': 'Accede de forma segura para sincronizar tus fechas y tareas.',
    'login.institution': 'Aula Virtual / Institución',
    'login.unemiPS': 'UNEMI presencial/semipresencial',
    'login.unemiOnline': 'UNEMI online',
    'login.upsdt': 'UPSDT',
    'login.username': 'Usuario / Correo',
    'login.usernamePlaceholder': 'ej. mi_usuario',
    'login.password': 'Contraseña',
    'login.passwordPlaceholder': '••••••••••••',
    'login.connectingBtn': 'Conectando con Moodle...',
    'login.connectBtn': 'Conectar Cuenta',
    'login.enterCredentials': 'Por favor, ingresa tu usuario y contraseña.',
    'login.connectedSuccess': '¡Conexión establecida con éxito!',
    'login.authFailed': 'La autenticación falló. Revisa tus credenciales.',
    'login.networkError': 'Error al conectar con el servidor. Revisa tu conexión de red o vuelve a intentarlo.',

    // NewTaskModal
    'modal.newTaskTitle': 'Programar Nueva Actividad',
    'modal.activityTitle': 'Título de la Actividad *',
    'modal.activityTitlePlaceholder': 'ej. Resolver cuestionario de Práctica 1',
    'modal.activityType': 'Tipo Actividad',
    'modal.typeManual': '⚙️ Actividad Manual',
    'modal.typeTask': '📝 Tarea Académica',
    'modal.typeQuiz': '📋 Cuestionario / Examen',
    'modal.typeActivity': '📚 General',
    'modal.deadline': 'Cierre (Fecha & Hora)',
    'modal.associateCourse': 'Asociar Materia',
    'modal.customCourseNone': 'Materia Personalizada / Ninguna',
    'modal.customCourseName': 'Nombre Materia Personalizada',
    'modal.customCoursePlaceholder': 'ej. Algebra Lineal o Investigaciones Libres',
    'modal.notes': 'Detalles / Anotaciones',
    'modal.notesPlaceholder': 'Apunta guías de estudio, temas de examen, compañeros de grupo...',
    'modal.cancel': 'Cancelar',
    'modal.save': 'Guardar Actividad',
    'modal.enterTitleAlert': 'Por favor, ingresa el título de la actividad.',

    // CSV export headers
    'csv.id': 'ID de Actividad',
    'csv.title': 'Título',
    'csv.type': 'Tipo Académico',
    'csv.group': 'Grupo / Individual',
    'csv.courseId': 'ID del Curso',
    'csv.courseName': 'Materia',
    'csv.url': 'Enlace de la Actividad',
    'csv.description': 'Detalle/Descripción',
    'csv.apertureIso': 'Fecha de Apertura (ISO)',
    'csv.apertureFormatted': 'Fecha de Apertura Formateada',
    'csv.closureIso': 'Fecha de Cierre (ISO)',
    'csv.closureFormatted': 'Fecha de Cierre Formateada',
    'csv.completed': 'Completada',
    'csv.registeredAt': 'Fecha de Registro',
    'csv.submissionStatus': 'Estado de Entrega',
    'csv.grade': 'Calificación',
    'csv.maxGrade': 'Calificación Máxima',
    'csv.gradingStatus': 'Estado de Calificación',
    'csv.feedback': 'Retroalimentación del Docente',
    'csv.individual': 'Individual',
    'csv.groupLabel': 'Grupal',
    'csv.yes': 'Sí',
    'csv.no': 'No',
    'csv.notSubmitted': 'No Entregado',
    'csv.toSubmit': 'Entregar',
    'csv.submitted': 'Entregado',
    'csv.graded': 'Calificado',
    'csv.gradeHidden': 'Calificación no visible',

    // App prompts & alerts
    'app.dueSoonTitle': '⏰ ¡Tienes actividades pendientes por vencer!',
    'app.dueSoonBody': 'Tienes {count} actividades de Moodle que cierran pronto.',
    'app.syncReminder3d': 'Han pasado 3 días desde tu última sincronización...',
    'app.syncReminder7d': 'Han pasado 7 días sin sincronizar tus materias...',
    'app.sessionExpiredAlert': 'La sesión de Moodle expiró o se cerró.',
    'app.syncDoneGlobal': '¡Sincronización completada con éxito!',
    'app.networkErrorViewHtml': 'Error de red al intentar cargar la página.',
    'app.viewHtmlError': 'Error al ver la página HTML de Moodle.',
    'app.noActiveSessionReconnect': 'No se encontró una sesión activa relacionada para esa actividad. Por favor ve a la pestaña "Conectar Moodle" y reconéctala.',
    'app.sessionExpired': 'La sesión expiró.',
    'app.singleTaskUpdateFailed': 'No se pudo actualizar de forma remota la actividad seleccionada.',
    'app.noActiveSessionDownload': 'No se encontró una sesión activa para esta cuenta. Por favor vuelve a conectar la cuenta.',
    'app.downloadHtmlError': 'Error al descargar la página de Moodle.',
    'app.networkErrorDownload': 'Error de red al intentar descargar la página.',
    'app.syncConnectAtLeastOne': 'Por favor conecta al menos una cuenta de Moodle para poder sincronizar.',
    'app.reconnectPrompt': 'Por favor, ingresa tus datos de acceso para volver a conectar tu cuenta.',
    'app.sessionsExpiredPrompt': 'Las cuentas o sesiones conectadas han expirado o se cerraron. Por favor ingresa tus datos de acceso en "Conectar Moodle" para continuar.',
    'app.connectionFailed': 'Conexión interrumpida ({error}). Vuelve a conectar e iniciar sesión.',
    
    // Notifications generated
    'notif.quizDueTodayTitle': '🏁 Examen/Test vence hoy',
    'notif.quizDueTodayBody': 'Test de "{title}" vence hoy a las {time}.',
    'notif.pendingDueTodayTitle': '⚠️ Entrega pendiente hoy',
    'notif.pendingDueTodayBody': 'La actividad "{title}" vence hoy y no ha sido entregada aún.',
    'notif.weeklySummaryTitle': '📅 Resumen semanal de pendientes',
    'notif.weeklySummaryBody': 'Tienes {tasks} tareas y {tests} tests para la próxima semana.',
    'notif.syncReminderTitle': '🔄 Recordatorio de Sincronización',
    'notif.syncReminderBody': 'Sincroniza tus actividades: No has sincronizado tus actividades desde hace {days} días.',
    'notif.newActivityTitle': '🆕 Nueva Actividad Detectada',
    'notif.newActivityBody': 'Materia: {course}\nCierre: {date}',
    'notif.deadlineChangeTitle': '📅 Cambio de Deadline',
    'notif.deadlineChangeBody': 'El plazo de "{title}" cambió de {oldDate} a {newDate}.',
    'notif.newGradeTitle': '⭐ Nueva Calificación',
    'notif.newGradeBody': 'Recibiste una nota para "{title}": {grade}/{gradeOver}.',
    'notif.statusUpdatedTitle': '🔄 Estado Actualizado',
    'notif.statusUpdatedBody': 'El estado de "{title}" cambió de "{oldStatus}" a "{newStatus}".'
  },
  en: {
    // Top Navbar
    'nav.title': 'Moodle Planner',
    'nav.subtitle': 'Moodle Virtual Classroom Manager',
    'nav.disconnected': 'Moodle Disconnected',
    'nav.setActive': 'Set active: {username}',
    'nav.notifications': 'Change notifications',
    'nav.activityAlerts': 'Activity Alerts',
    'nav.markRead': 'Mark read',
    'nav.clear': 'Clear',
    'nav.integratedNotifications': '🔔 Integrated notifications',
    'nav.notificationsEnabled': 'Enabled',
    'nav.notificationsEnableBtn': 'Enable',
    'nav.noNotifications': 'No notifications!',
    'nav.noNotificationsDesc': 'Changes to your courses will be announced here whenever you sync.',
    'nav.smartAlerts': 'Smart Moodle Alerts',
    'nav.notifBrowserGranted': 'Browser notifications enabled!',
    'nav.notifBrowserPrompt': 'Please enable notifications in your browser URL lock icon.',
    'nav.switchLanguage': 'Switch language',

    // Main Navigation Tabs
    'tab.agenda': 'My Agenda',
    'tab.connections': 'Connections',
    'tab.stats': 'Statistics',
    'tab.sandbox': 'Sandbox',
    'tab.newTask': '+ New Task',
    'tab.newTaskTitle': 'Create new manual task',

    // SyncStatusBar
    'sync.syncBtn': 'Sync',
    'sync.syncingBtn': 'Syncing...',
    'sync.connectFirst': 'Connect an account first',
    'sync.syncAllActive': 'Sync courses for all active accounts',
    'sync.account': 'account',
    'sync.accounts': 'accounts',
    'sync.viewAccountDetails': 'View details per account',
    'sync.lastSynced': 'Last synced: {time}',
    'sync.notSyncedRecently': 'Not synced recently',
    'sync.tasksCompleted': '({completed}/{total} completed)',
    'sync.legendTitle': 'Icon and status guide',
    'sync.icons': 'Icons',
    'sync.legendHeading': 'Indicator Guide',
    'sync.legend.imminent': 'Imminent (<30h)',
    'sync.legend.excellent': 'Excellent (≥90%)',
    'sync.legend.pending': 'Pending (<10d)',
    'sync.legend.acceptable': 'Acceptable (80-89%)',
    'sync.legend.ungraded': 'Ungraded',
    'sync.legend.regular': 'Average (60-79%)',
    'sync.legend.overdue': 'Overdue',
    'sync.legend.failed': 'Failing (<60%)',
    'sync.progressOf': '{current} of {total} courses',
    'sync.cancel': 'Cancel',
    'sync.connecting': 'Connecting to Moodle...',
    'sync.analyzing': 'Analyzing activities...',
    'sync.upToDate': 'Up to date',
    'sync.error': 'Error',
    'sync.ready': 'Ready',
    'sync.viewLog': 'View log',
    'sync.emptyBanner': 'Connect your Moodle account to automatically sync your courses and tasks.',
    'sync.connect': 'Connect',

    // Relative times
    'time.justNow': 'just now',
    'time.minutesAgo': '{min}m ago',
    'time.hoursAgo': '{hrs} hrs ago',
    'time.daysAgo': '{days} d ago',
    'time.completed': 'Completed',
    'time.noDeadline': 'No deadline',
    'time.closedOverdue': 'Closed/Overdue',
    'time.oneDayHrsLeft': '1 day and {hrs} hrs left',
    'time.daysLeft': '{days} days left',
    'time.minutesLeft': '{mins} minutes left!',
    'time.hoursLeft': '{hrs} hours left!',

    // Connections List in App.tsx
    'conn.connectedAccounts': 'Connected Accounts ({count})',
    'conn.verifyingSession': 'Verifying session...',
    'conn.sessionExpired': '(Session Expired)',
    'conn.currentBrowser': '(Current Browser)',
    'conn.reconnect': 'Reconnect',
    'conn.viewActivities': 'View activities',
    'conn.viewBrowser': 'View browser',
    'conn.removeAccount': 'Remove Account',
    'conn.logOut': 'Log Out',

    // Developer Sandbox in App.tsx
    'dev.title': 'Developer Sandbox & Event Tracker Logs',
    'dev.desc': 'Explore Moodle interactively through our security proxy. All your interactions (button clicks, links, and file upload metadata) are logged in real-time in the event console for technical analysis.',
    'dev.clearConfirm': 'Are you sure you want to clear the event logs history?',
    'dev.clearBtn': 'Clear Logs',
    'dev.clearTooltip': 'Clear all recorded events',
    'dev.noConnectionsTitle': 'No Active Moodle Connections',
    'dev.noConnectionsDesc': 'This section requires a connected Moodle session. Go to the Connections section to sign in with your credentials.',
    'dev.connectNowBtn': 'Connect Moodle Now',
    'dev.activeSessionLabel': 'Active Session:',
    'dev.homeDashboardTooltip': 'Go to home dashboard (/my/)',
    'dev.reloadTooltip': 'Reload page',
    'dev.proxyLabel': 'HTTP PROXY',
    'dev.goBtn': 'Go',
    'dev.loadingProxy': 'Loading Moodle proxy browser...',
    'dev.eventLogsTitle': 'Detected Event Logs',
    'dev.eventsCount': '{count} events',
    'dev.userInteractionsDesc': 'Recorded user interactions:',
    'dev.copyJson': 'Copy JSON',
    'dev.copiedSuccess': 'Logs copied to clipboard successfully.',
    'dev.waitingInteractions': 'Waiting for interactions in browser...',
    'dev.waitingInteractionsDesc': 'Click on courses, buttons or choose files to upload to see live logs.',
    'dev.element': 'Element:',
    'dev.id': 'ID:',
    'dev.class': 'Class:',
    'dev.href': 'Href:',
    'dev.field': 'Field:',
    'dev.size': 'Size:',
    'dev.type': 'Type:',
    'dev.untitled': '(Untitled)',

    // ActivityTimeline
    'timeline.localTime': 'Local time (Ecuador):',
    'timeline.searchPlaceholder': 'Search activity...',
    'timeline.accountsFilter': 'Accounts',
    'timeline.allCourses': 'All Courses',
    'timeline.allTypes': 'All Types',
    'timeline.typeTask': 'Assignments',
    'timeline.typeQuiz': 'Quizzes',
    'timeline.typeActivity': 'Activities',
    'timeline.typeManual': 'Manual',
    'timeline.done': 'Done',
    'timeline.hideCompleted': 'Hide completed',
    'timeline.showCompleted': 'Show completed',
    'timeline.downloadCsv': 'Download CSV',
    'timeline.clearAgenda': 'Clear Agenda',
    'timeline.confirmClear': 'CONFIRM CLEAR AGENDA?',
    'timeline.filterByAccount': 'Filter by account:',
    'timeline.allAccounts': 'All Accounts ({count})',
    'timeline.activeFilters': '{count} active filter{plural}',
    'timeline.filterAccountsTitle': 'Filter Accounts / Careers',
    'timeline.noOptions': 'No options available',
    'timeline.manualTasks': 'Manual / Local Tasks',
    'timeline.manualTasksCareer': 'Manual Tasks ({carrera})',
    'timeline.other': 'Other',
    'timeline.statsPending': '{count} pending',
    'timeline.statsCompleted': '{count} completed',
    'timeline.statsProgress': '{percent}% progress',
    'timeline.weekTitle': 'Week {number}',
    'timeline.weekSpecial': 'Special / Extra Week',
    'timeline.weekNoDeadline': 'Activities without specific deadline',
    'timeline.currentWeekBadge': 'Current week',
    'timeline.groupBadge': 'Group',
    'timeline.opening': 'Opening...',
    'timeline.updating': 'Updating...',
    'timeline.downloading': 'Downloading...',
    'timeline.viewDocument': 'View document',
    'timeline.downloadHtml': 'Download HTML',
    'timeline.rescan': 'Re-scan',
    'timeline.viewInMoodle': 'View on Moodle',
    'timeline.grade': 'Grade:',
    'timeline.feedback': 'Feedback:',
    'timeline.attachedFeedbackImages': 'Attached feedback images:',
    'timeline.aperture': 'Opened:',
    'timeline.closure': 'Closed:',
    'timeline.importantNotice': 'Important notice:',
    'timeline.noFilteredActivities': 'No activities match the filters',
    'timeline.emptyAgendaTitle': 'Your agenda is empty!',
    'timeline.emptyAgendaDesc': 'Go to "Explore Moodle" and click "Sync All Courses" or add a manual task.',
    'timeline.clearAgendaConfirm': 'Are you sure you want to clear the entire local agenda?',
    'timeline.reopenedWarning': '⚠️ This assignment was overdue, but is currently open for late submission or second attempt.',
    'timeline.overdueWarning': '⚠️ This task has passed its official submission deadline.',
    'timeline.viewRawHtml': 'View HTML',

    // StatsPanel
    'stats.title': 'Academic Performance by Course',
    'stats.subtitle': 'Your courses ordered from lowest to highest average. Overdue unsubmitted tasks penalize with',
    'stats.filterLabel': 'Filter performance by account:',
    'stats.allAccounts': 'All Accounts ({count})',
    'stats.activeFilters': '{count} active filter{plural}',
    'stats.filterModalTitle': 'Filter Accounts / Careers',
    'stats.clear': 'Clear',
    'stats.noOptions': 'No options available',
    'stats.manualTasksLocal': 'Manual / Local Tasks',
    'stats.manualTasksCareer': 'Manual Tasks ({carrera})',
    'stats.emptyAlert': 'No graded or overdue activities registered in your agenda yet.',
    'stats.emptyAlertSub': 'Sync your courses in "Explore Moodle" to download your actual grades.',
    'stats.highestAlert': 'Highest Alert ⭐',
    'stats.generalAvg': 'Overall Average 📈',
    'stats.totalAccumulated': 'Cumulative Total',
    'stats.bestPerformance': 'Best Performance ✨',
    'stats.courseLabel': 'Course {number}',
    'stats.unsubmitted': '{count} unsubmitted',
    'stats.graded': '{count} graded',
    'stats.noGrades': 'No grades',
    'stats.breakdown': 'Grade Breakdown ({count} items analyzed)',
    'stats.viewUpcoming': 'View upcoming activities',
    'stats.noCourseGrades': 'No grades recorded for this course.',
    'stats.overdueUnsubmitted': 'Unsubmitted (Overdue)',
    'stats.moodleGrade': 'Moodle Grade',
    'stats.closedDate': 'Closed: {date}',

    // LoginPanel
    'login.connected': 'Moodle Connected',
    'login.user': 'User:',
    'login.disconnect': 'Disconnect',
    'login.connectTitle': 'Connect Virtual Classroom',
    'login.connectSubtitle': 'Securely access to synchronize your deadlines and assignments.',
    'login.institution': 'Virtual Classroom / Institution',
    'login.unemiPS': 'UNEMI in-person/semi-presential',
    'login.unemiOnline': 'UNEMI online',
    'login.upsdt': 'UPSDT',
    'login.username': 'Username / Email',
    'login.usernamePlaceholder': 'e.g. my_username',
    'login.password': 'Password',
    'login.passwordPlaceholder': '••••••••••••',
    'login.connectingBtn': 'Connecting to Moodle...',
    'login.connectBtn': 'Connect Account',
    'login.enterCredentials': 'Please enter your username and password.',
    'login.connectedSuccess': 'Connection established successfully!',
    'login.authFailed': 'Authentication failed. Check your credentials.',
    'login.networkError': 'Error connecting to the server. Check your network connection or try again.',

    // NewTaskModal
    'modal.newTaskTitle': 'Schedule New Activity',
    'modal.activityTitle': 'Activity Title *',
    'modal.activityTitlePlaceholder': 'e.g. Complete Practice Quiz 1',
    'modal.activityType': 'Activity Type',
    'modal.typeManual': '⚙️ Manual Activity',
    'modal.typeTask': '📝 Academic Assignment',
    'modal.typeQuiz': '📋 Quiz / Exam',
    'modal.typeActivity': '📚 General Activity',
    'modal.deadline': 'Deadline (Date & Time)',
    'modal.associateCourse': 'Associate Course',
    'modal.customCourseNone': 'Custom Course / None',
    'modal.customCourseName': 'Custom Course Name',
    'modal.customCoursePlaceholder': 'e.g. Linear Algebra or Independent Research',
    'modal.notes': 'Details / Notes',
    'modal.notesPlaceholder': 'Note study guides, exam topics, group members...',
    'modal.cancel': 'Cancel',
    'modal.save': 'Save Activity',
    'modal.enterTitleAlert': 'Please enter the activity title.',

    // CSV export headers
    'csv.id': 'Activity ID',
    'csv.title': 'Title',
    'csv.type': 'Academic Type',
    'csv.group': 'Group / Individual',
    'csv.courseId': 'Course ID',
    'csv.courseName': 'Course',
    'csv.url': 'Activity Link',
    'csv.description': 'Detail/Description',
    'csv.apertureIso': 'Opening Date (ISO)',
    'csv.apertureFormatted': 'Formatted Opening Date',
    'csv.closureIso': 'Closing Date (ISO)',
    'csv.closureFormatted': 'Formatted Closing Date',
    'csv.completed': 'Completed',
    'csv.registeredAt': 'Registration Date',
    'csv.submissionStatus': 'Submission Status',
    'csv.grade': 'Grade',
    'csv.maxGrade': 'Max Grade',
    'csv.gradingStatus': 'Grading Status',
    'csv.feedback': 'Teacher Feedback',
    'csv.individual': 'Individual',
    'csv.groupLabel': 'Group',
    'csv.yes': 'Yes',
    'csv.no': 'No',
    'csv.notSubmitted': 'Not Submitted',
    'csv.toSubmit': 'To Submit',
    'csv.submitted': 'Submitted',
    'csv.graded': 'Graded',
    'csv.gradeHidden': 'Grade not visible',

    // App prompts & alerts
    'app.dueSoonTitle': '⏰ You have pending activities due soon!',
    'app.dueSoonBody': 'You have {count} Moodle activities closing soon.',
    'app.syncReminder3d': '3 days have passed since your last sync...',
    'app.syncReminder7d': '7 days have passed without syncing your courses...',
    'app.sessionExpiredAlert': 'Moodle session expired or closed.',
    'app.syncDoneGlobal': 'Sync completed successfully!',
    'app.networkErrorViewHtml': 'Network error while attempting to load the page.',
    'app.viewHtmlError': 'Error viewing Moodle HTML page.',
    'app.noActiveSessionReconnect': 'No active session found for this activity. Please go to "Connections" and reconnect it.',
    'app.sessionExpired': 'Session expired.',
    'app.singleTaskUpdateFailed': 'Could not remotely update the selected activity.',
    'app.noActiveSessionDownload': 'No active session found for this account. Please reconnect the account.',
    'app.downloadHtmlError': 'Error downloading Moodle page.',
    'app.networkErrorDownload': 'Network error while trying to download the page.',
    'app.syncConnectAtLeastOne': 'Please connect at least one Moodle account to synchronize.',
    'app.reconnectPrompt': 'Please enter your login credentials to reconnect your account.',
    'app.sessionsExpiredPrompt': 'Connected accounts or sessions have expired or were closed. Please enter your credentials under "Connections" to continue.',
    'app.connectionFailed': 'Connection interrupted ({error}). Reconnect and log in again.',

    // Notifications generated
    'notif.quizDueTodayTitle': '🏁 Exam/Quiz due today',
    'notif.quizDueTodayBody': 'Quiz for "{title}" is due today at {time}.',
    'notif.pendingDueTodayTitle': '⚠️ Pending submission today',
    'notif.pendingDueTodayBody': 'Activity "{title}" is due today and has not been submitted yet.',
    'notif.weeklySummaryTitle': '📅 Weekly pending summary',
    'notif.weeklySummaryBody': 'You have {tasks} assignments and {tests} quizzes for next week.',
    'notif.syncReminderTitle': '🔄 Sync Reminder',
    'notif.syncReminderBody': 'Sync your activities: You haven\'t synced your activities in {days} days.',
    'notif.newActivityTitle': '🆕 New Activity Detected',
    'notif.newActivityBody': 'Course: {course}\nDeadline: {date}',
    'notif.deadlineChangeTitle': '📅 Deadline Changed',
    'notif.deadlineChangeBody': 'Deadline for "{title}" changed from {oldDate} to {newDate}.',
    'notif.newGradeTitle': '⭐ New Grade',
    'notif.newGradeBody': 'You received a grade for "{title}": {grade}/{gradeOver}.',
    'notif.statusUpdatedTitle': '🔄 Status Updated',
    'notif.statusUpdatedBody': 'Status for "{title}" changed from "{oldStatus}" to "{newStatus}".'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    try {
      const saved = localStorage.getItem('app_language');
      if (saved === 'en' || saved === 'es') return saved;
      // Default to Spanish as the original app was in Spanish, or check browser
      const navLang = navigator.language?.toLowerCase() || '';
      return navLang.startsWith('es') ? 'es' : 'es';
    } catch {
      return 'es';
    }
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem('app_language', lang);
    } catch (e) {
      console.error(e);
    }
  };

  const toggleLanguage = () => {
    setLanguage(language === 'es' ? 'en' : 'es');
  };

  const t = (key: string, fallbackOrVars?: string | Record<string, any>, vars?: Record<string, any>): string => {
    let fallback = '';
    let actualVars: Record<string, any> | undefined = undefined;

    if (typeof fallbackOrVars === 'string') {
      fallback = fallbackOrVars;
      actualVars = vars;
    } else if (fallbackOrVars && typeof fallbackOrVars === 'object') {
      actualVars = fallbackOrVars;
    }

    const dict = translations[language] || translations.es;
    let text = dict[key] || translations.es[key] || fallback || key;

    if (actualVars) {
      Object.entries(actualVars).forEach(([k, v]) => {
        text = text.replace(new RegExp(`\\{${k}\\}`, 'g'), String(v));
      });
    }

    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
